language: python
python:
- '2.5'
- '2.6'
- '2.7'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
- pip install coverage coveralls
script:
- coverage run -m --branch pytest -vs test
- coverage report -m
after_success:
- coveralls

